//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Networking_Project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class MoviesTbl
    {
        [Key, Column(Order = 1)]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int idScreen { get; set; }

        [Required(ErrorMessage = "this field is required.")]
       
        public string Name { get; set; }
        [DataType(DataType.DateTime)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy HH:mm}")]
        [Display(Name = "Start Time")]
        [Required(ErrorMessage = "this field is required.")]
        public System.DateTime StartTime { get; set; }

        [DataType(DataType.DateTime)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy HH:mm}")]
        [Display(Name = "End Time")]
        [Required(ErrorMessage = "this field is required.")]
        public System.DateTime EndTime { get; set; }


        [Required(ErrorMessage = "this field is required.")]
        public string Hall { get; set; }


        [Display(Name = "Number Seats")]
        [Required(ErrorMessage = "this field is required.")]
        public int NumberSeats { get; set; }

        [Required(ErrorMessage = "this field is required.")]
        [Display(Name = "Ticket Price")]
        public double TicketPrice { get; set; }
        [Display(Name = "Age Min")]
        public Nullable<int> AgeMin { get; set; }
        public string Category { get; set; }
        public Nullable<int> Rank { get; set; }

        public byte[] Poster { get; set; }
    }
}
