//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Networking_Project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class OrdersTbl
    {
        [Key, Column(Order = 1)]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int idOrder { get; set; }
        public int idUser { get; set; }
        public int idScreen { get; set; }

        [Required(ErrorMessage = "this field is required.")]
        public int Chair { get; set; }
        public bool Pay { get; set; }
        public string Status { get; set; }

        [Required(ErrorMessage = "this field is required.")]

        //[RegularExpression(@"^(?:4[0-9]{12}(?:[0-9]{3})?|[25][1-7][0-9]{14}|6(?:011|5[0-9][0-9])[0-9]{12}|3[47][0-9]{13}|3(?:0[0-5]|[68][0-9])[0-9]{11}|(?:2131|1800|35\d{3})\d{11})$")]
        public int NumberCard { get; set; }


        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM/yy }")]
        [Required(ErrorMessage = "this field is required.")]
        public System.DateTime Validity { get; set; }

        [Required(ErrorMessage = "this field is required.")]
        //[RegularExpression(@"0-9,0-9,0-9$")]
        public int validation { get; set; }
    }
}
